### ISSUE TITLE
composer.json , Installationspfad falsch

### ISSUE THREAD

**Issue by BugBuster1701** [pixelSpreadde/twentytwenty#2]
[Hier](https://github.com/Sascha-Brandhoff/twentytwenty/blob/master/composer.json#L31) steht:

```
"system/modules/flip_ce"
```

Sollte doch bestimmt sein:

```
"system/modules/twentytwenty"
```

**Comment by BugBuster1701** [comment]
Bei der Gelegenheit kannst du auch gleich dieses anpassen:

```
"contao/core": ">=3.4,<3.5"
```

zu 

```
"contao/core": ">=3.5,<3.6"
```

dann passt es zum ER2.

**Comment by Sascha-Brandhoff** [comment]
Danke, habs angepasst.
